# HW 7 - Libraries + Modules
ULAB - Physics and Astronomy Division \
Due **Wednesday, November 6th, 2024 at 11:59pm** on Gradescope

--------------------------------------------------------------

## Module vs. Package vs. Library
### Module
A **module** is a single file containing Python code (typically ending in a `.py` extension) that contains functions and variables. 
- They can be imported into other Python files or notebooks
- You use modules to organize code into smaller, reuseable parts
- Ex: `even_sum.py` that we created during lecture.

*You will create your OWN module for this homework and use that we made during class.*

### Package
A **package** is a group of modules, organized like a directory. 
- A package requires a special `__init__.py` file to tell Python that the ENTIRE directory is something you would like to import.
- Packages can contain sub-pacakges
- Ex: `BAGLE_Microlensing` is an example of a package (if you are in Dex's group, this should be familar to you). Or you could think of `paarti` if you are in Brianna's group.

*You will NOT be working with a package for this homework.*

### Library
A **library** is a much broader term that also refers to a collection of modules (like a package) but a library can also contain mulitple packages. 
- Libraries serve a much wider range of functionality for
- Programmers use packages to have ready-to-go tools that can be used for data manipulation, web development, machine learning or simulations.
- Ex: `numpy` is a very common library. Later in this course we will also be working some of the following libraries `matplotlib`, `scipy`, and `astropy`, `pandas`, etc

*You WILL be working with the extensive numpy library for this homework!*

--------------------------------------------------------------

# 1 NumPy
**NumPy** (aka Numerical Python) is a library that was designed for caring out computations in Python. 

We did not have a ton of time to work through examples during class, so I will ask that you check out this website for more information: https://numpy.org/doc/ 

Before we can work through any problems, you need to call the following in your notebook:

In [24]:
import numpy as np

## 1.1 Lists vs. Arrays
*When I first started working with NumPy I didn't understand what was so special about arrays. This homework problem should help illustrate the difference. Make sure to follow each step and follow good coding practices.*

1) Make a list called `my_list` and make an array called `my_arr` with the same values. There is an example below, but don't copy mine! Ex:
```
my_list = [11, 12, 13, 14, 15]
my_arr = np.array([11, 12, 13, 14, 15])
```
*Notice that to use the `numpy` package we had to call its short cut `np` and then call upon its funciton `.array()`. This is similar to working with a built-in python function like `.append()`.*

In [4]:
my_list = [10, 20, 30, 40, 50]
my_arr = np.array([10, 20, 30, 40, 50])

2) Multiply `my_list` by 4 and multiply `my_arr` by 4. Print the results. Describe what happens in a comment.

In [9]:
print(my_list * 4)
print(my_arr * 4)

#multiplying the list by 4 returns a list which just repreats the original list 4 times
#multiplying the array by 4 returns the values in the array multiplied by 4

[10, 20, 30, 40, 50, 10, 20, 30, 40, 50, 10, 20, 30, 40, 50, 10, 20, 30, 40, 50]
[ 40  80 120 160 200]


3) Add `my_list` with `my_list`. Add `my_arr` with `my_arr`. Add `my_list` with `my_arr`. Print the results. Describe what happens in a comment.

In [15]:
print(my_list + my_list) #returns the same list appended onto the first list
print(my_arr + my_arr) #returns the values with the same indexes added together, ex: 40 + 40 = 80
print(my_list + my_arr) #also returns the values with the same indexes added together

[10, 20, 30, 40, 50, 10, 20, 30, 40, 50]
[ 20  40  60  80 100]
[ 20  40  60  80 100]


4) Subtract `my_list` with `my_list`. Subtract `my_arr` with `my_arr`. Subtract `my_list` with `my_arr`. Print the results. Describe what happens in a comment.

In [27]:
#print(my_list - my_list) - this returns an error, cannot subtract using a - operator
difference = [x - y for x, y in zip(my_list, my_list)]
print(difference) #this returns each value subtracted from the corresponding value

print(my_arr - my_arr) #subtracts each value from the value with the correspoding index in the other array
print(my_list - my_arr) #subtracts each value from the value with the correspoding index in the array

[0, 0, 0, 0, 0]
[0 0 0 0 0]
[0 0 0 0 0]


5) Multiply `my_list` with `my_list`. Multply `my_arr` with `my_arr`. Multiply `my_list` with `my_arr`. Print the results. Describe what happens in a comment.

In [31]:
# print(my_list * my_list) - this returns an error, cannot multiply lists directly
product = [x * y for x, y in zip(my_list, my_list)]
print(product) #this returns each component in the list multiplied by a component in the other my_list

print(my_arr * my_arr) #multiplies each component by the component with the corresponding index in the other array
print(my_list * my_arr) #multiplies each component by the component with the corresponding index in the other array

[100, 400, 900, 1600, 2500]
[ 100  400  900 1600 2500]
[ 100  400  900 1600 2500]


7) Divide `my_list` with `my_list`. Divide `my_arr` with `my_arr`. Divide `my_list` with `my_arr`. Print the results. Describe what happens in a comment.

In [39]:
#print(my_list / my_list) - returns an error, cannot directly divide two lists
quotient = [x / y for x, y in zip(my_list, my_list)]
print(quotient) #this returns each component in the list divided by a component in the other my_list as floats with a zero afer the decimal

print(my_arr / my_arr) #divides each component by the component with the corresponding index in the other array, returns quotients as floats with no zero afer the decimal
print(my_list / my_arr) #divides each component by the component with the corresponding index in the array, returns quotients as floats with no zero afer the decimal

[1.0, 1.0, 1.0, 1.0, 1.0]
[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]


8) After working through this problem, in at least two sentences, describe the difference between a list and an array.

In [33]:
#You cannot apply most mathematical operations directly to a list, except for + but this appends one lsit to the end of the other, it doesn't actually add the components.
#On the other hand, arrays can have mathematical operations applied directly to them and the operations will be performed on the components of the array itself.

## 1.2 Nested List and Multi-Dimensional Arrays
A **nested list** is when you have a list as an element for a list. Example:
```
nested_list = [[1, 2, 3], [4, 5, 6]]
```

A **multi-dimensional array** is essentially a nested list, but it contains the properties of a matrix. Example:
```
multi_d_array = np.array([[1, 2, 3], [4, 5, 6]])
```

Go to this website for more information on NumPy: https://www.w3schools.com/python/numpy/default.asp

Write a **function** that takes in a two-dimensional array. Example:

```
arr3 = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18]])
```

and then returns the second value in each row. Example:

```
[4, 10, 16]
```

In [229]:
def second_value_from_each_row(arr):
    #this function returns the second  value in each row
    second_values = [row[1] for row in arr]
    print(second_values)

#test case 1
arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
second_value_from_each_row(arr1)

[2, 5, 8]


In 2-3 sentences, describe what section of the website helped you write your function. 

In [ ]:
# I looked at the NumPy Array Indexing section, specifically accessing 2-D arrays. 
#I also did some additional research to figure out how to apply the method they showed to multiple rows, not jsut a specific one

How would you take a nested list and return the second value in each row? Explain in 2-3 sentences and show an example.

## 1.3 Up to You!
With the website I just gave you: https://www.w3schools.com/python/numpy/default.asp

I recommend working through the examples they provide (you don't have to do all of them, but a few would be good). It will help you build an intuition for numpy. It won't take very long, there are only a couple of examples per section.

Write you own **function** that follows the theme of one of the sections (i.e. array reshaping, array filter, random intro, etc). For example, if you are curious about the section "**NumPy Creating Arrays**" you could write a function that creates a multi-dimensional array.

```

>>> def make_multi_dimensional_array(one_d_array, dimensions):
...     # Creates a multi-dimensional array
...     # Your code here
...     return # Your code here

>>> my_one_d_array = [2, 4, 6, 8]
>>> my_dimension = 10
>>> ten_d_array = make_multi_dimensional_array(my_one_d_array, my_dimension)
>>> print(ten_d_array)
[[[[[[[[[[2 4 6 8]]]]]]]]]]

```

Your function should be more detailed than the example I gave you. Include at least one of the following: 
- a conditional statement
- an assignment operator
- a loop (`for` or `while`)
- `if`, `elif`, `else`, statement

In [237]:
#Iterating Arrays
arr2 = np.array([-1, 2, -3, 4, -5, 6, 77, 80, 99, 100, 111, 120])
def less_than_6_add100_orbiggerthan100(arr):
    #this function will either tell us that a number is less than 6, add 100 to the number if the number is between 6 and 100, or tell us that it is a very large number
    for i in arr:
        if i <6:
            print(f"{i} is less than 6")
        elif 6 <= i < 100:
            print(i)
        else:
            print("wow that's a big number!")

less_than_6_add100_orbiggerthan100(arr2)
#change so it actually makes sense

-1 is less than 6
2 is less than 6
-3 is less than 6
4 is less than 6
-5 is less than 6
6
77
80
99
wow that's a big number!
wow that's a big number!
wow that's a big number!


In the section you took inspiration from, show all of the examples below. Follow good coding practices and give at least two test cases for each example. Don't forget comments! \
\
*For my example, I took inspiration from **NumPy Creating Arrays** so I would show following examples with DIFFERENT test cases: Create a NumPy ndarray Object, Dimensions in Arrays ,0-D Arrays, 1-D Arrays, 2-D Arrays, 3-D Arrays, Check Number of Dimensions, Higher Dimensional Arrays.*

In [235]:
#I took inspiration from NumPy Iterating Arrays
#Example 1 - iterating on the elements of a 1-D array
def iterating_on_1Darray(arr):
    #this functions prints all elements of the array
    for x in arr:
        print(x)

#testcase1
arr_1 = np.array([0, 2, 4])
iterating_on_1Darray(arr_1)

#testcase2
arr_01 = np.array([10, 25, 7])
iterating_on_1Darray(arr_01)

#EX2: Iterating on 2D arrays
def iterating_on_2Darray(arr):
    for x in arr:
        print(x)

#testcase1
arr_2 = np.array([[1, 2, 3], [4, 5, 6]])
iterating_on_2Darray(arr_2)

#testcase2
arr_02 = np.array([[10, 20, 30], [40, 50, 60]])
iterating_on_2Darray(arr_02)

#EX3:Iterating 3-D Arrays
def iterating_on_3Darray(arr):
    for x in arr:
        print(x)

#testcase1
arr_3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
iterating_on_3Darray(arr_3)

#testcase2
arr_03 = np.array([[[10, 20, 30], [40, 50, 60]], [[70, 80, 90], [100, 110, 120]]])
iterating_on_3Darray(arr_03)

#Ex4: Iterating arrays using nditer
def iterate_using_nditer(arr):
   for x in np.nditer(arr):
       print(x)

#testcase1
arr_4 = np.array([[[1, 2, 31], [4, 13, 6]], [[7, 8, 90], [10, 11, 12]]])
iterate_using_nditer(arr_4)

#testcase2
arr_04 = np.array([[[10, 21, 30], [40, 56, 60]], [[77, 80, 90], [101, 110, 120]]])
iterate_using_nditer(arr_04)

#EX5: Iterating Array With Different Data Types
def changing_datatype_while_iterating(arr):
    #this function will change the data in the array into string data when iterating through the array
    for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
        print(x)

#testcase1
arr_5 = np.array([1, 14, 6])
changing_datatype_while_iterating(arr_5)

#testcase2
arr_05 = np.array([6, 2, 8])
changing_datatype_while_iterating(arr_05)

#EX6: Iterating with different step size
def iterate_skipping_1_element(arr):
    #this fucntion iterates through the array, skipping 1 element
    for x in np.nditer(arr[:, ::2]):
        print(x)

#test case 1
arr_6 = np.array([[11, 12, 13], [14, 15, 16]])
iterate_skipping_1_element(arr_6)

#test case 2
arr_06 = np.array([[11, 21, 31], [41, 51, 61]])
iterate_skipping_1_element(arr_06)

#EX7: Enumerated Iteration Using ndenumerate()
def enumerate(arr):
    #provides us with the index of the data point as well as the data point
    for idx, x in np.ndenumerate(arr):
        print(idx, x)

#test case 1
arr_7 = np.array([11, 22, 33])
enumerate(arr_7)

#test case 2
arr_07 = np.array([[17, 27, 37], [47, 517, 67]])
enumerate(arr_07)

0
2
4
10
25
7
[1 2 3]
[4 5 6]
[10 20 30]
[40 50 60]
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[10 20 30]
 [40 50 60]]
[[ 70  80  90]
 [100 110 120]]
1
2
31
4
13
6
7
8
90
10
11
12
10
21
30
40
56
60
77
80
90
101
110
120
b'1'
b'14'
b'6'
b'6'
b'2'
b'8'
11
13
14
16
11
31
41
61
(0,) 11
(1,) 22
(2,) 33
(0, 0) 17
(0, 1) 27
(0, 2) 37
(1, 0) 47
(1, 1) 517
(1, 2) 67


In 2-3 sentences, describe how your function took inspiration from a section.\
\
*For my example, `make_multi_dimensional_array`, I would talk about the **NumPy Creating Arrays** section and how I took inspiration from the example **Higher Dimensional Arrays**.*

In [37]:
#I took inspiration from this section because I wanted to iterate through my array and only print certain values.
#

# 2 Brianna's Module
During lecture we created and worked with a module called `even_sum.py`. Import that module here. 

In [10]:
import even_sum as es

Now that you have imported the module. Call the module and the first function with your own list of numbers. 

In [14]:
list_1 = [11, 22, 33, 44, 55, 66, 77, 88, 99]
es.sum_even_numbers(list_1)

220

I have provided you a separate module called `example.py`. Import that module here.

In [241]:
import example as ex

With the following variables, use my module to show which of the rocket's escape!

In [244]:
rocket_velocities = np.array([
    [1000, 5000, 8000, 12000],  # Rocket 1's velocity at different times
    [2000, 6000, 9000, 10000],  # Rocket 2
    [3000, 3100, 3200, 3300]    # Rocket 3
])

mass_of_planet = 5.972e24 # kilograms
radius_of_planet = 6.371e6 # meters

In [246]:
ex.escape_velocity(mass_of_planet, radius_of_planet) #this function calculates escape velocity
ex.orbital_velocity(mass_of_planet, radius_of_planet) #this function calculates orbital velocity

ex.rocket_launch(rocket_velocities, mass_of_planet, radius_of_planet) #this function determines how well the rocket launch will go

['Rocket left the planet!',
 'Rocket is orbiting around the planet.',
 'Rocket crashes back into the planet!']

In 2-3 sentences describe how this code follows "good coding practices" and where there is room for improvement.

In [248]:
#All of the functions have very clear naming and there are comments explaining exactly what each fucntion does.
#However, in the returns of the rocket.launch fucntion could be improved. It is unclear which rocket has which path, so dialogue could be changed to reflect that.

# 3 Your Turn!
Now its your turn to make a module! Choose a topic from a class (could be physics, computer science, nuclear engineering, biology, astronomy, math, or an topic that interests you!) and build a module around it! Look at my module called `example.py` and base your structure around it. Your module NEEDS to include the following.

Overall:
1) Your module needs to use at least one NumPy function: https://numpy.org/devdocs/reference/routines.math.html
2) Your module needs to contain a multi-dimensional array: https://numpy.org/devdocs/reference/arrays.ndarray.html 
3) Your module needs **at least** three functions that follow good coding practices.
4) Inside your function, include comments. Don't forget to describe what the function is doing and what the inputs and outputs are.
5) Your module needs either a `for` loop or `while` loop.
6) Your module needs an `if`, `elif`, and `else` statement.
7) Your module needs at least two assignment variables (`+=`, `*=`, etc).
8) Creativity. *If it looks like you plugged this whole thing into ChatGPT, I will take off points. You can use ChatGPT to help you code, but you can't use it to just do your homework for you. That's no fun :(*

In 2-3 sentences, describe the topic of your module and its capabilities. 

In [ ]:
#My module focuses on determining whether or not a planets are in the habitable zone of a star.
#My module includes fucntions to calculate absolute visual magnitude, bolometric magnitude, absolute lumnosity, the inner and outer boundaries of the habitable zone, and finally determines if planets are inside the habitable zone. 
#It is capable of taking in multidimensional arrays. I designed it in this way so that it could take in multiple measurements for a singular planet 

In 2-3 sentences, answer the following. What was the most challenging part of building this module? What did you learn in the process that you can apply to future coding assignments?

In [30]:
#The most challenging part of this module was figuring out how to handle multidimensional arrays. At first I took a slightly different approach to what my multidimensional array represent, having each inner array represent a set of planets at similar extremes away from the star. From this I learned how to write a function which can process values from each row of an array. 
#I also learned how to apply numpy functions like np.mean which will probably be helpful for future coding assignments involving mathmatical operations.

Once your module is complete, import it here.

In [317]:
import habitable_zone as hz
import numpy as np

In [319]:
import importlib
importlib.reload(hz)

<module 'habitable_zone' from 'C:\\Users\\jacek\\ulab\\ulab_mariadubiel\\homework7\\habitable_zone.py'>

Call each of your functions in the cell below. Make sure to show the outputs! 

In [322]:
star1_apparent_magnitude = -1.46
star1_distance = 2.64 #in parsecs
star1_planet_distances = np.array([
    [66, 60, 69, 70], #planet 1 measurements
    [0.9, 0.87, 0.85, 0.89], #planet 2 measurements
    [2, 2.1, 1.9, 2.3], #planet 3 measurements
    [4, 4.2, 4.1, 4.7], #planet 4 measurements
    [5, 4.6, 7.6, 3.9], #planet 5 measurments
    [20, 21, 22.3, 21.3]]) #planet 6 measurements
star1_bolometric_correction_constant = -0.3

In [324]:
hz.absolute_visual_magnitude(star1_apparent_magnitude, star1_distance)

1.431980365650845

In [326]:
hz.bolometric_magnitude(1.431980365650845, star1_bolometric_correction_constant)

1.131980365650845

In [328]:
hz.calculate_abs_luminosity(1.131980365650845)

14.352078537396618

In [330]:
hz.inner_boundary(14.352078537396618)

3.6121107575635074

In [332]:
hz.outer_boundary(14.352078537396618)

5.203786454764076

In [334]:
hz.is_it_in_habitable_zone(star1_planet_distances, 3.6121107575635074, 5.203786454764076)

Planet is too far!
Planet is too close!
Planet is too close!
Planet is in habitable zone!!
Planet is too far!
Planet is too far!


'Number of planets in habitable zone:1, Number of planets outside habitable zone:5'

# 4 Proper Submission
To recieve full credit for this assignment make sure you do the following:

1) Copy this homework assignment from the `ulab_2024` repository into **YOUR** local `homework7` branch. It will contain this notebook and an additional file called `example.py`. 
   
2) Follow the tasks. Make sure to run all the cells so that **all** output is visible. You will get points taken off if your ouputs are not shown!

3) Add/commit/push this notebook and **ANY** modules (so you should have `example.py` and your module) used in this homework assignment to your remote `homework7` branch. Make sure to have NOTHING else in your branch (i.e. no previous homeworks or lecture notes).

4) Do the following:
- Take a screenshot of moving **into or out** of your `homework7` brach, call it `hw7_branch`.
- Take a screenshot of calling `ls` in your `homework7` branch, it should only contain items relevent to homework 7, call it `hw7_ls`.
- Take a screenshot of adding this assignment to your local `homework7` branch, call it `hw7_add`.
- Take a screenshot of committing this assignment to your local `homework7` branch, call it `hw7_commit`.
- Take a screenshot of pushing this assignment to your remote `homework7` branch, call it `hw7_push`. 

6) Include these screenshots in your `homework7` branch. Upload your `homework7` branch to Gradescope!